# Generated by Django 3.2.16 on 2024-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, max_length=1024000, null=True, upload_to='category/images'),
        ),
    ]
