# Generated by Django 3.2.16 on 2024-05-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='shops.category'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, max_length=1024000, null=True, upload_to='category/images')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.cabinets')),
            ],
        ),
    ]
